<a href="https://colab.research.google.com/github/SisekoC/My-Notebooks/blob/main/higherOrderGradient.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print("Version of tensorflow is : ",tf.__version__)
import numpy as np

Version of tensorflow is :  2.17.0


In [2]:
x = tf.Variable([[4.0]])
with tf.GradientTape() as tape:
    loss = tf.square(x)
dx = tape.gradient(loss , x)
print("Value of dx : ",dx.numpy())
print("dx   : ",dx)
print("loss :" , loss)

Value of dx :  [[8.]]
dx   :  tf.Tensor([[8.]], shape=(1, 1), dtype=float32)
loss : tf.Tensor([[16.]], shape=(1, 1), dtype=float32)


In [3]:
x = tf.Variable([4.0])
with tf.GradientTape() as tape:
    loss = tf.square(x)
dx = tape.gradient(loss , x)
print("Value of dx : ",dx.numpy())
print("dx   : ",dx)
print("loss :" , loss)

Value of dx :  [8.]
dx   :  tf.Tensor([8.], shape=(1,), dtype=float32)
loss : tf.Tensor([16.], shape=(1,), dtype=float32)


In [4]:
x = tf.Variable(4.0)
with tf.GradientTape() as tape:
    loss = tf.square(x)
dx = tape.gradient(loss , x)
print("Value of dx : ",dx.numpy())
print("dx   : ",dx)
print("loss :" , loss)

Value of dx :  8.0
dx   :  tf.Tensor(8.0, shape=(), dtype=float32)
loss : tf.Tensor(16.0, shape=(), dtype=float32)


In [5]:
x = tf.ones((2,2))
with tf.GradientTape() as t:
    t.watch(x)
    y = tf.reduce_sum(x)
    z = tf.square(y)
dz_dx = t.gradient(z , x)
print("dz_dx : ",dz_dx)
print("z : ",z)
print("y : ",y)
print("x : ",x)

dz_dx :  tf.Tensor(
[[8. 8.]
 [8. 8.]], shape=(2, 2), dtype=float32)
z :  tf.Tensor(16.0, shape=(), dtype=float32)
y :  tf.Tensor(4.0, shape=(), dtype=float32)
x :  tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


**Persistent & Higher_order derivatives**

In [6]:
x = tf.Variable(2.0)
with tf.GradientTape(persistent=True) as t: #GradientTape.gradient can only be called once on non-persistent tapes.(if don't use persistent=True)
    t.watch(x)
    y = x * x
    z = y * y
print("dy_dx : ",t.gradient(y , x))
print("dz_dx : ",t.gradient(z, x))
print("dz_dy : ",t.gradient(z , y))
print("d2y_dx2 : ",t.gradient(t.gradient(y , x) , x))

dy_dx :  tf.Tensor(4.0, shape=(), dtype=float32)
dz_dx :  tf.Tensor(32.0, shape=(), dtype=float32)
dz_dy :  tf.Tensor(8.0, shape=(), dtype=float32)
d2y_dx2 :  None


In [7]:
x = tf.Variable(3.0)
with tf.GradientTape() as t1:
    with tf.GradientTape() as t2:
        y = x * x * x
    dy_dx = t2.gradient(y , x)
d2y_dx2 = t1.gradient(dy_dx , x)

print("dy_dx   : ",dy_dx)
print("d2y_dx2 : ",d2y_dx2)

dy_dx   :  tf.Tensor(27.0, shape=(), dtype=float32)
d2y_dx2 :  tf.Tensor(18.0, shape=(), dtype=float32)
