<a href="https://colab.research.google.com/github/SisekoC/My-Notebooks/blob/main/self_attention.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Self-attention

In [3]:
import numpy as np
import tensorflow as tf

##Step 1: Preparing inputs

In [4]:
x = [[1, 0, 1, 0],  # input 1
     [0, 2, 0, 2],  # input 2
     [1, 1, 1, 1]]  # input 3

x = np.array(x, dtype=np.float32)

##Step 2 Initialize the weights

In [5]:
w_key = [[0, 0, 1],
         [1, 1, 0],
         [0, 1, 0],
         [1, 1, 0]]

w_query = [[1, 0, 1],
           [1, 0, 0],
           [0, 0, 1],
           [0, 1, 1]]

w_value = [[0, 2, 1],
           [0, 3, 0],
           [1, 0, 3],
           [1, 1, 0]]

w_key = np.array(w_key, dtype=np.float32)
w_query = np.array(w_query, dtype=np.float32)
w_value = np.array(w_value, dtype=np.float32)

##Step 3 Determine key, query and value

In [6]:
keys = x @ w_key
querys = x @ w_query
values = x @ w_value

print('Keys: \n', keys)
print('Querys: \n', querys)
print('Values: \n', values)

Keys: 
 [[0. 1. 1.]
 [4. 4. 0.]
 [2. 3. 1.]]
Querys: 
 [[1. 0. 2.]
 [2. 2. 2.]
 [2. 1. 3.]]
Values: 
 [[1. 2. 4.]
 [2. 8. 0.]
 [2. 6. 4.]]


##Step 4 Calculate attention scores

In [7]:
attn_scores = querys @ keys.T
print(attn_scores)

[[ 2.  4.  4.]
 [ 4. 16. 12.]
 [ 4. 12. 10.]]


##Step 5 Calculate softmax

In [8]:
attn_scores_softmax = np.round_(tf.nn.softmax(attn_scores, axis=-1), decimals=1)
print(attn_scores_softmax)

[[0.1 0.5 0.5]
 [0.  1.  0. ]
 [0.  0.9 0.1]]


##Step 6 Multiplying scores and values

In [9]:
weighted_values = values[:, None] * attn_scores_softmax.T[:, :, None]
print(weighted_values)

[[[0.1 0.2 0.4]
  [0.  0.  0. ]
  [0.  0.  0. ]]

 [[1.  4.  0. ]
  [2.  8.  0. ]
  [1.8 7.2 0. ]]

 [[1.  3.  2. ]
  [0.  0.  0. ]
  [0.2 0.6 0.4]]]


##Step 7 Sum of weighted values

In [10]:
outputs = np.sum(weighted_values, axis=0)
print(outputs)

[[2.1       7.2       2.4      ]
 [2.        8.        0.       ]
 [2.        7.7999997 0.4      ]]
